# Generated by Django 5.2 on 2025-04-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questio_text',
            new_name='question_text',
        ),
    ]
